[package]
name = "open-steam-controller"
version = "1.2.0"
edition = "2021"
authors = ["Lennard Kittner"]
description = "A CLI and tray application for monitoring and managing the new Steam Controller."

[dependencies]
anyhow = "1.0.102"
bitflags = "2.12.1"
clap = { version = "4.5.32", features = ["derive"] }
const_format = { version = "0.2.36", features = ["derive"] }
hidapi = "2.6.6"
thistermination = "1.0.0"
[target.'cfg(target_os = "linux")'.dependencies]
dialog = "0.3.0"
ksni = "0.2.0"
shell-escape = "0.1.5"
dbus = "0.9"
uinput = "0.1.3"

[target.'cfg(not(target_os = "linux"))'.dependencies]
tray-icon = "0.21.3"
winit = "0.30.13"

[target.'cfg(target_os = "windows")'.dependencies]
image = "0.25.10"
winreg = "0.56.0"
windows = { version = "0.62.2", features = [
    "Win32_System_LibraryLoader",
] }
vigem-client = "0.1.4"
